; semicolon in column 1 for comment
[Settings]

; Title used by setup
InstTitle=RunGTAP

; default dir to install to (user can change)
InstDir=C:\runGTAP375


; name of exe to be installed
exename=RunGTAP.exe

; title for desktop shortcut to EXENAME (see above)
ShortCutTitle=RunGTAP 3.75


; name of zip to unpack
Zipname=RunGTAP.7z

; disk space needed
DiskNeededMB=850

; end of INI file

