; semicolon in column 1 for comment
[Settings]

; Title used by setup
InstTitle=GTPAgg2 

; default dir to install to (user can change)
InstDir=C:\GTPAg2 

; name of exe to be installed
exename=GTAPAgg2.exe

; title for desktop shortcut to EXENAME (see above)
ShortCutTitle=GTAPAgg2 

; name of zip to unpack
Zipname=GTAPAgg2.zip

; disk space needed: a bit more than size of unzipped ZIP contents
DiskNeededMB=700

; end of INI file

