file gtapPARM = default.prm;
Verbal Description =
Numeraire shock;
Method = Johansen;
Steps = 1;
automatic accuracy = no;
subintervals = 1;
exogenous
          pop
          psaveslack pfactwld
          profitslack incomeslack endwslack
          cgdslack tradslack
          ams atm atf ats atd
          aosec aoreg avasec avareg
          afcom afsec afreg afecom afesec afereg
          aoall afall afeall
          au dppriv dpgov dpsave
          to tp tm tms tx txs
          qo(ENDW_COMM,REG) ;
Rest Endogenous ;

Shock pfactwld = uniform 10;
